export const names = [
    'Ajani Goldmane',
    'Aminatou',
    'Angrath',
    'Arlinn Kord',
    'Ashiok',
    'Chandra Nalaar',
    'Dack Fayden',
    'Daretti',
    'Davriel Cane',
    'Domri Rade',
    'Dovin Baan',
    'Estrid',
    'Elspeth Tirel',
    'Garruk Wildspeaker',
    'Gideon Jura',
    'Huatli',
    'Inzerva',
    'Jace Beleren',
    'Jaya Ballard',
    'Jiang Yanggu',
    'Karn',
    'Kasmina',
    'Kaya',
    'Kiora',
    'Koth',
    'Liliana Vess',
    'Mu Yanling',
    'Nahiri',
    'Narset',
    'Nicol Bolas (Desparked)',
    'Nissa Revane',
    'Ob Nixilis',
    'Oko',
    'Ral Zarek',
    'Rowan Kenrith',
    'Saheeli Rai',
    'Samut',
    'Sarkhan Vol',
    'Sorin Markov',
    'Tamiyo',
    'Teferi',
    'Tezzeret',
    'Teyo Verada',
    'The Wanderer',
    'Tibalt',
    'Ugin',
    'Venser',
    'Vivien Reid',
    'Vraska',
    'Will Kenrith',
    'Wrenn',
    'Xenagos',

    'Bo Levar',
    'Commodore Guff',
    'Daria',
    'Freyalise',
    'Kristina of the Woods',
    'Taysir of Rabiah',
    'Tevesh Szat',
    'Urza',
    'Lord Windgrace',
    'Azor',
    'Dakkon Blackblade[7]',
    'Dyfed (dead)',
    'Feroz (dead)',
    'Jaya Ballard',
    'Jeska',
    'Karn',
    'Leshrac (dead)',
    'Liliana Vess',
    'Manatarqua (dead)',
    'Meshuvel',
    'Nahiri',
    'Nicol Bolas',
    'Ob Nixilis',
    'Parcher',
    'Ravi',
    'Sandruu',
    'Sorin Markov',
    'Serra (dead)',
    'Slobad',
    'Teferi',
    'Ugin',

    'Embereck',
    'Daria',
    'Eskil',
    'Faralyn',
    'Fatima',
    'Feroz',
    'Freyalise',
    'Gerheart',
    'Geyadrone Dihada',
    'Grenfell Mor of Golthonor',
    'Jared Carthalion',
    'Kenan Sahrmal',
    'Krim',
    'Kristina of the Woods',
    'Leshrac',
    'Liana of Minorad',
    'Windgrace',
    'Platon',
    'Rafthrasa',
    'Ravi',
    'Ravidel',
    'Sandruu',
    'Serra',
    'Taysir of Rabiah',
    'Teferi',
    'Tempé',
    'Terrent Amese',
    'Tevesh Szat',
    'The Ancients',
    'The Thorn',
    'Thomil',
    'The Tolgath',
    'Urza',
    'Vram',
    'Worzel',
    'Yawden',
]
